# Generated by Django 6.0.5 on 2026-05-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='create_data',
            new_name='create_date',
        ),
    ]
